version: '2'

services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
    networks:
      - reverse-proxy

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

  cockpit:
    image: agentejo/cockpit
    environment:
      # uncomment and complete these lines to enable letsencrypt support
      # (only works on domains accessible from outside):
      LETSENCRYPT_HOST: api.pxlwrx.de
      LETSENCRYPT_EMAIL: admin@pxlwrx.de

      PORT: 80
      VIRTUAL_HOST: api.pxlwrx.de
    networks:
      - reverse-proxy

networks:
  reverse-proxy: