version: '2'

services:

  prometheus_srv:
    image: prom/prometheus
    container_name: prometheus_server
    hostname: prometheus_server
    networks:
      - reverse-proxy

  prometheus_node:
    image: prom/node-exporter
    container_name: prom_node_exporter
    hostname: prom_node_exporter
    depends_on:
      - prometheus_srv
    networks:
      - reverse-proxy

  grafana:
    image: grafana/grafana
    container_name: grafana_server
    hostname: grafana_server
    depends_on:
      - prometheus_srv
    networks:
      - reverse-proxy
    environment:
      # uncomment and complete these lines to enable letsencrypt support
      # (only works on domains accessible from outside):
      LETSENCRYPT_HOST: metrics.pxlwrx.de
      LETSENCRYPT_EMAIL: admin@pxlwrx.de

      PORT: 80
      VIRTUAL_HOST: metrics.pxlwrx.de

networks:
  reverse-proxy:
    external:
      name: reverse-proxy